### ISSUE TITLE
CONTRIBUTING.md is unclear on the structure of contributions

### ISSUE THREAD

**Issue by goetzk** [pubtestme/pubtestme.github.io#1]
While README clearly explains the format of contributions it fails to expand on what should actually be included.

Should a contributor provide
- a list of links
- an exerpt from each link supporting the claim
- a bit of explanatory text (composed by them) with a collection of links
- or something else again?

This will become eaiser as references are added, but for now the contribution curve may be quite steep.

**Comment by amboar** [comment]
I'm happy with any of the above for the moment 😀. Roughly, I'm thinking a page per incident, such as the sports grants incident, and we add external links to the incident page. The incident page should have a short description of the issue. The landing page should have a time ordered list of incidents. At some point we should have an interactive timeline graphic, but let's start simple first.

**Comment by amboar** [comment]
Here's an example of a contribution:

https://github.com/pubtestme/pubtestme.github.io/blame/master/_posts/2020-01-15-award-of-funding-under-the-community-sport-infrastructure-program.md

**Comment by amboar** [comment]
Just a note that I moved the readme content into the about page. Probably needs some further massaging, will get to that at some point in the near future

**Comment by amboar** [comment]
I've updated the issue templates to help out a bit. Do you think we've done enough work to close this issue @goetzk ?

**Comment by goetzk** [comment]
Lets do that - any further refinements can be tracked separately.
